### ISSUE TITLE
Corrections to session 9 and 10

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-project-multilingual#66]
- [x] - Session 9#6 asks to connect with your coach, which might work the some way on global

- [x] - Session 9#7 tells you to go to www.2414now.net, an english  website

- [x] - Session 10#2 asks to connect with your coach, which might work the some way on global

- [x] -Session 10#6 Has a bunch of links that are US only (like: become a county coordinator)
